CREATE TABLE IF NOT EXISTS wallets (
    id            VARCHAR(64) PRIMARY KEY,
    currency      VARCHAR(8)  NOT NULL,
    balance       BIGINT      NOT NULL CHECK (balance >= 0),
    version       BIGINT      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transfers (
    id                    VARCHAR(64) PRIMARY KEY,
    source_wallet_id      VARCHAR(64) NOT NULL,
    destination_wallet_id VARCHAR(64) NOT NULL,
    amount                BIGINT      NOT NULL CHECK (amount > 0),
    currency              VARCHAR(8)  NOT NULL,
    reference             VARCHAR(128),
    status                VARCHAR(32) NOT NULL,
    created_at            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transfer_source FOREIGN KEY (source_wallet_id) REFERENCES wallets(id),
    CONSTRAINT fk_transfer_dest   FOREIGN KEY (destination_wallet_id) REFERENCES wallets(id)
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    request_hash    VARCHAR(128) NOT NULL,
    transfer_id     VARCHAR(64),
    http_status     INT          NOT NULL,
    response_body   CLOB         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transfer_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id   VARCHAR(64),
    event_type    VARCHAR(64) NOT NULL,
    details       VARCHAR(512),
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id  VARCHAR(64) NOT NULL,
    event_type    VARCHAR(64) NOT NULL,
    payload       CLOB        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_outbox_transfer_completed UNIQUE (aggregate_id, event_type)
);
