-- Wallet Transfer Service — initial schema
-- All monetary amounts are stored as BIGINT minor units (e.g. AED fils).
-- H2 is run in PostgreSQL compatibility mode; this DDL is valid for both.

CREATE TABLE wallets (
    id         VARCHAR(64)  PRIMARY KEY,
    balance    BIGINT       NOT NULL CHECK (balance >= 0),
    currency   VARCHAR(8)   NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transfers (
    id                    VARCHAR(64)  PRIMARY KEY,
    source_wallet_id      VARCHAR(64)  NOT NULL REFERENCES wallets(id),
    destination_wallet_id VARCHAR(64)  NOT NULL REFERENCES wallets(id),
    amount                BIGINT       NOT NULL CHECK (amount > 0),
    currency              VARCHAR(8)   NOT NULL,
    reference             VARCHAR(128),
    status                VARCHAR(16)  NOT NULL,
    idempotency_key       VARCHAR(128),
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transfers_status_check
        CHECK (status IN ('completed','failed'))
);

-- Idempotency store — separate from transfers so the key lifecycle is
-- observable and the same key can point at either success or failure.
CREATE TABLE idempotency_keys (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    payload_hash    VARCHAR(64)  NOT NULL,
    transfer_id     VARCHAR(64)  REFERENCES transfers(id),
    response_status INT          NOT NULL,
    response_body   CLOB         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transfer_events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id VARCHAR(64)  NOT NULL REFERENCES transfers(id),
    event_type  VARCHAR(64)  NOT NULL,
    payload     CLOB,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE outbox_events (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id  VARCHAR(64) NOT NULL,
    event_type    VARCHAR(64) NOT NULL,
    payload       CLOB        NOT NULL,
    published_at  TIMESTAMP,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One outbox row per completed transfer — enforces exactly-once emission at
-- write-time regardless of retries or concurrent duplicates.
CREATE UNIQUE INDEX ux_outbox_transfer_completed
    ON outbox_events(aggregate_id, event_type);

CREATE INDEX ix_transfers_idem ON transfers(idempotency_key);
CREATE INDEX ix_events_transfer ON transfer_events(transfer_id);
CREATE INDEX ix_outbox_unpublished ON outbox_events(published_at);
